name: Go

on:
  push:
    tags:
      - '*'

jobs:
  build_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o linux_amd64/AnimeGo cmd/animego/main.go && tar -czvf AnimeGo_linux_amd64.tar.gz -C linux_amd64 AnimeGo
          CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -ldflags="-s -w" -o linux_386/AnimeGo cmd/animego/main.go && tar -czvf AnimeGo_linux_386.tar.gz -C linux_386 AnimeGo
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o linux_arm64/AnimeGo cmd/animego/main.go && tar -czvf AnimeGo_linux_arm64.tar.gz -C linux_arm64 AnimeGo
          CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -ldflags="-s -w" -o linux_arm/AnimeGo cmd/animego/main.go && tar -czvf AnimeGo_linux_arm.tar.gz -C linux_arm AnimeGo
          
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o darwin_amd64/AnimeGo cmd/animego/main.go && tar -czvf AnimeGo_darwin_amd64.tar.gz -C darwin_amd64 AnimeGo
          
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o windows_amd64/AnimeGo.exe cmd/animego/main.go && zip AnimeGo_windows_amd64.zip -j windows_amd64/AnimeGo.exe
          CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -ldflags="-s -w" -o windows_386/AnimeGo.exe cmd/animego/main.go && zip AnimeGo_windows_386.zip -j windows_386/AnimeGo.exe
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "AnimeGo*.tar.gz,AnimeGo*.zip"
          bodyFile: ""
          token: ${{secrets.GITHUB_TOKEN}}
